# GitHub Pages configuration
title: "3D Визуализация полетов Ютэйр"
description: "Интерактивное 3D приложение для визуализации маршрутов авиакомпании Ютэйр"
baseurl: "/hackaton"
url: "https://punkcot.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - .github
  - docs
  - src
  - tests
  - Dockerfile
  - docker-compose.yml
  - Makefile
  - .dockerignore
  - .env
  - .specstory

# Include files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
